### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by pritamkarmakar** [agomezmoron/screen-recorder#7]
This error randomly popping up for a testng tests. Could you please look into it?

`java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at com.github.agomezmoron.multimedia.testng.listener.VideoRecorderListener.endVideo(VideoRecorderListener.java:113)
        at com.github.agomezmoron.multimedia.testng.listener.VideoRecorderListener.onTestSuccess(VideoRecorderListener.java:70)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1735)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:744)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
        at org.testng.SuiteRunner.run(SuiteRunner.java:289)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
        at org.testng.TestNG.runSuites(TestNG.java:1144)
        at org.testng.TestNG.run(TestNG.java:1115)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
`

**Comment by agomezmoron** [comment]
Hi @pritamkarmakar,

It seems the video couldn't be created. Is this error occurring during a parallel testing? Do you have permissions in that folder?

Thanks!

**Comment by pritamkarmakar** [comment]
Thanks, @agomezmoron for your reply. Yes it was a permission issue.
